<?php
include '../includes/db.php';
include '../includes/auth.php';
require_role(["admin", "manager"]);

if (!isset($_GET['id'])) {
    die("Invalid request");
}

$id = intval($_GET['id']);

// Fetch payroll and employee details
$query = "
SELECT p.*, u.username, e.base_salary, u.email, u.phone, b.name AS branch_name
FROM payroll p
JOIN employees e ON p.`user-id` = e.id
JOIN users u ON e.`user-id` = u.id
LEFT JOIN branch b ON u.`branch-id` = b.id
WHERE p.id = '$id'
";
$result = mysqli_query($conn, $query);
$p = mysqli_fetch_assoc($result);

if (!$p) {
    die("Payslip not found");
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Payslip - <?php echo htmlspecialchars($p['username']); ?></title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/payrollPayslip.css">
</head>
<body>
<div class="payslip">
  <div class="print-btn">
    <button class="btn btn-primary" onclick="window.print()"><i class="fa fa-print"></i> Print Payslip</button>
  </div>

  <div class="header">
    <h3>Employee Payslip</h3>
    <p><strong>Month:</strong> <?php echo htmlspecialchars($p['month']); ?></p>
  </div>

  <div class="row mb-4">
    <div class="col-md-6">
      <h6><strong>Employee Information</strong></h6>
      <p><b>Name:</b> <?php echo htmlspecialchars($p['username']); ?></p>
      <p><b>Email:</b> <?php echo htmlspecialchars($p['email']); ?></p>
      <p><b>Phone:</b> <?php echo htmlspecialchars($p['phone']); ?></p>
      <p><b>Branch:</b> <?php echo htmlspecialchars($p['branch_name'] ?? 'N/A'); ?></p>
    </div>
    <div class="col-md-6">
      <h6><strong>Payroll Details</strong></h6>
      <p><b>Status:</b> <?php echo htmlspecialchars($p['status']); ?></p>
      <p><b>Date Generated:</b> <?php echo date("d M Y", strtotime($p['created_at'] ?? 'now')); ?></p>
    </div>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Earnings</th>
        <th>Amount (UGX)</th>
        <th>Deductions</th>
        <th>Amount (UGX)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Base Salary</td><td><?php echo number_format($p['base_salary'], 2); ?></td>
        <td>NSSF</td><td><?php echo number_format($p['nssf'], 2); ?></td>
      </tr>
      <tr>
        <td>Transport</td><td><?php echo number_format($p['transport'], 2); ?></td>
        <td>Tax (PAYE)</td><td><?php echo number_format($p['tax'], 2); ?></td>
      </tr>
      <tr>
        <td>Housing</td><td><?php echo number_format($p['housing'], 2); ?></td>
        <td>Loan</td><td><?php echo number_format($p['loan'], 2); ?></td>
      </tr>
      <tr>
        <td>Medical</td><td><?php echo number_format($p['medical'], 2); ?></td>
        <td>Other Deductions</td><td><?php echo number_format($p['other_deductions'], 2); ?></td>
      </tr>
      <tr>
        <td>Overtime</td><td><?php echo number_format($p['overtime'], 2); ?></td>
        <td></td><td></td>
      </tr>
      <tr class="table-success">
        <th>Gross Salary</th><td><b><?php echo number_format($p['gross_salary'], 2); ?></b></td>
        <th>Total Deductions</th>
        <td><b><?php echo number_format($p['nssf'] + $p['tax'] + $p['loan'] + $p['other_deductions'], 2); ?></b></td>
      </tr>
      <tr class="table-primary">
        <th colspan="2">Net Salary (Take Home)</th>
        <th colspan="2"><b>UGX <?php echo number_format($p['net_salary'], 2); ?></b></th>
      </tr>
    </tbody>
  </table>

  <div class="footer">
    <p>Generated by Payroll System — <?php echo date("d M Y"); ?></p>
  </div>
</div>
</body>
</html>
